import{a as E,S,i as l}from"./assets/vendor-BLPZKqeQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const R="50447683-96da9a4ff1c3a2668348e0aa0",$="https://pixabay.com/api/",q=15;async function f(o,r=1){const n={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:r};return(await E.get($,{params:n})).data}const g=document.querySelector(".gallery"),p=document.getElementById("loader"),h=document.getElementById("load-more");let d;function y(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:i,comments:P,downloads:B})=>`
      <li class="gallery-card">
        <a href="${s}" class="gallery-item">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${P}</p>
          <p><b>Downloads:</b> ${B}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){g.innerHTML=""}function L(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function w(){h.classList.remove("hidden")}function v(){h.classList.add("hidden")}const m=document.querySelector(".form"),I=document.getElementById("load-more");let c="",a=1,u=0;m.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){l.warning({message:"Please enter a search term!",position:"topRight"});return}c=r,a=1,M(),v(),L();try{const n=await f(c,a);u=n.totalHits,n.hits.length===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(n.hits),u>a*15&&w())}catch(n){l.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(n)}finally{b()}m.reset()});I.addEventListener("click",async()=>{if(c){a+=1,v(),L();try{const o=await f(c,a);y(o.hits),a*15>=u?l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(o){l.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}finally{b()}}});
//# sourceMappingURL=index.js.map
