import{a as E,S,i as c}from"./assets/vendor-BLPZKqeQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const R="50447683-96da9a4ff1c3a2668348e0aa0",$="https://pixabay.com/api/",q=15;async function f(o,r=1){const n={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:r};return(await E.get($,{params:n})).data}const p=document.querySelector(".gallery"),h=document.getElementById("loader"),y=document.getElementById("load-more");let d;function L(o){const r=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:P,downloads:B})=>`
      <li class="gallery-card">
        <a href="${a}" class="gallery-item">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${P}</p>
          <p><b>Downloads:</b> ${B}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){p.innerHTML=""}function b(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}function w(){y.classList.remove("hidden")}function v(){y.classList.add("hidden")}const g=document.querySelector(".form"),I=document.getElementById("load-more");let u="",s=1,m=0;g.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){c.warning({message:"Please enter a search term!",position:"topRight"});return}u=r,s=1,M(),v(),b();try{const n=await f(u,s);m=n.totalHits,l(),n.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(L(n.hits),m>s*15&&w())}catch(n){l(),c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(n)}g.reset()});I.addEventListener("click",async()=>{s+=1,v(),b();try{const o=await f(u,s);l(),L(o.hits),s*15>=m?c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(o){l(),c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}});
//# sourceMappingURL=index.js.map
