import{a as b,S as w,i}from"./assets/vendor-BLPZKqeQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const L="50447683-96da9a4ff1c3a2668348e0aa0",P="https://pixabay.com/api/",E=15;async function g(o,r=1){const a={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:r};return(await b.get(P,{params:a})).data}const m=document.querySelector(".gallery");document.getElementById("loader");document.getElementById("load-more");let c;function p(o){const r=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:n,comments:f,downloads:h})=>`
      <li class="gallery-card">
        <a href="${s}" class="gallery-item">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${f}</p>
          <p><b>Downloads:</b> ${h}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){m.innerHTML=""}const u=document.querySelector(".form"),S=document.getElementById("load-more");let d="",l=1,y=0;u.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.warning({message:"Please enter a search term!",position:"topRight"});return}d=r,l=1,v();try{const a=await g(d,l);y=a.totalHits,a.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):p(a.hits)}catch(a){i.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(a)}u.reset()});S.addEventListener("click",async()=>{l+=1;try{const o=await g(d,l);p(o.hits),l*15>=y&&i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(o){i.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}});
//# sourceMappingURL=index.js.map
